AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda para registrar datos obtenidos de un archivo en base64

  Template SAM para procesamiento de archivos y registro de datos

Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: registrar_datos_archivo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Environment:
        Variables:
          IS_LOCAL: ""
      Events:
        ProcessFile:
          Type: Api
          Properties:
            Path: /registro-datos-archivo
            Method: POST
        OptionsProcess: # No desplegar este event
          Type: Api
          Properties:
            Path: /registro-datos-archivo
            Method: OPTIONS

Outputs:
  HelloWorldAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
