AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda para registrar datos obtenidos de un archivo en base64

  Template SAM para procesamiento de archivos y registro de datos

Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  LoadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: registrar_datos_archivo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Environment:
        Variables:
          IS_LOCAL: ""
      Events:
        ProcessFile:
          Type: Api
          Properties:
            Path: /registro-datos-archivo
            Method: POST

Outputs:
  LoadFileAPI:
    Description: API Gateway endpoint URL for test environment
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
